n = input('Digite algo: ')
print('O tipo desse valor é: ', type(n))
print('É um número?', n.isnumeric())
print('É alfabético?',n.isalpha())
print('É alfanumérico?',n.isalnum())
print('Está em maiuscula?',n.isupper())
print('Está em minúscula? ',n.islower())
print('Está capitalizada?',n.istitle())